### ISSUE TITLE
After updating 3.0 project not working in iOS Safari. 

### ISSUE THREAD

**Issue by ti-hardikshah** [zappar-xr/universal-ar-unity#7] opened 2021-12-21 09:42 UTC
**Describe the bug**
I am working with Unity 2019.4.33 || 2020.3 || 2021.2.6

**To Reproduce**
Add Zap work using git and Add sample file 
Open Scene Image traking 
Build WebGL and test on iPhone safari

**Expected behavior**
The app should work but get stuck at the black screen even not ask for camera permission. 

**Smartphone (please complete the following information):**
 - Device:iPhone XR
 - OS: [e.g. iOs 14.8 , 15.2]
 - Browser [safari]
 - Version [latest]

**Comment by nfynt-zap** [comment] 2021-12-21 11:20
Hi @ti-hardikshah,

We weren't able to reproduce the same over iPhone safari! Can you confirm 
- if you're upgrading from old UAR version (which one)?
- if it's working in editor?
- have you configure zappar SRP in case you're using unity universal render pipeline?

Also note if you're upgrading from older UAR version, you would need to update your Unity scene as well. As this is a major release and there are major changes compared to older version especially with respect to Tracking and camera, and other editor level changes. Please refer to [CHANGELOG.md](https://github.com/zappar-xr/universal-ar-unity/blob/main/CHANGELOG.md) to compare the new developments, and [README.md](https://github.com/zappar-xr/universal-ar-unity/blob/main/README.md) to understand the new flow.

Regards,

**Comment by ti-hardikshah** [comment] 2021-12-21 11:31
Hello @nfynt-zap 
I am just using an Inbuilt pipeline and building sample demo, it works on Chrome but not working on safari. 
Give me 15 min I'll update Video as well as a testing link. 

I am using Unity 2020.3.24, as well I had tests on 2019.4.36 and unity 2021.2.6 

I am not using SRP. 

Its work on iPhone 11 but not working on iPhone XR, I had tested on 2 different OS version: 15.2 & 14.8

**Comment by ti-hardikshah** [comment] 2021-12-21 11:42
@nfynt-zap 
Here is the testing link: https://fpzjo.zappar.io/2948006917381701143/6.5/ 
and Here is a video link : https://youtu.be/mj_9Z7ejNKs

**Comment by nfynt-zap** [comment] 2021-12-21 13:01
Hi @ti-hardikshah,

Can you provide a minimum reproducible unity project for this? 

I am afraid it might be project specific than anything to do with UAR! We tested the sample scene with iPhone XR on ios15.1 and iPhone 6 on ios 12.5 and it seems to work fine.

Also, did you try clearing your browser cache and taking a debug build to see what's wrong. At least on my iPod ios15.1 the site and permission loads fine but the unity scene update is extremely sluggish!

**Comment by nfynt-zap** [comment] 2021-12-21 13:15
Also I notice the project is using WebGL 2.0 which is only supported on ios15.1 and above devices and not an ideal choice at the moment for Safari. You may wanna try using WebGL 1.0 graphics API from Unity WebGL player settings for better support.

**Comment by ti-hardikshah** [comment] 2021-12-21 13:56
I had set Auto in graphics API, let me try with WebGL 1.0. 
I had set Auto because in unity 2021 WebGL 1.0 is depricated 

and before 15 days all work well even in XR safari.

**Comment by ti-hardikshah** [comment] 2021-12-21 14:01
Even I have tested with WebGL 1.0 setting unity 2021.2.6 with ZapWork 3.0.0 but still does not work.

**Comment by ti-hardikshah** [comment] 2021-12-21 14:10
@nfynt-zap 
Here is the demo project link 
https://we.tl/t-dcE2sEEsrM
Unity 2019.4.33 for the same version I am facing the same issue.

**Comment by ti-hardikshah** [comment] 2021-12-21 14:13
@nfynt-zap  I had noticed one more thing, for a few tests it work well for iPhone XR safari, but after a few iterations of the update build it stop working in safari. so I had clean Safari catch from setting but still not working

**Comment by nfynt-zap** [comment] 2021-12-21 14:41
@ti-hardikshah Thanks for sharing the project.

It seems you were using Zappar WebGL template on Unity 2019, where it should have been Zappar2019 ([please refer to docs](https://github.com/zappar-xr/universal-ar-unity#webgl)).

Here's the build I published using the same project: https://rqkek.zappar.io/56995127745125615/0.1.2/
Can you confirm it works fine on your end? I tested on iPod ios15.1 and Android and everything seems normal.

**Comment by ti-hardikshah** [comment] 2021-12-21 15:04
@nfynt-zap I have tried both for 2019. and for unity 2020 I am using the Zappar template only.

**Comment by ti-hardikshah** [comment] 2021-12-21 15:06
@nfynt-zap  
using your lin i am getting this error in my device 
![Skype_Picture_2021_12_21T15_05_42_633Z](https://user-images.githubusercontent.com/60419705/146952151-cd4265d4-d471-4a3f-af9d-4aae3a5c1947.jpeg)

**Comment by ti-hardikshah** [comment] 2021-12-21 15:08
Using your testing link I am getting this error on iPhone XR 
![Skype_Picture_2021_12_21T15_07_47_665Z](https://user-images.githubusercontent.com/60419705/146952457-16d837ad-048a-4f8b-ad62-d129335aa5c7.jpeg)

**Comment by nfynt-zap** [comment] 2021-12-21 17:30
We were able to test this on iPhone XR and didn't encounter this on our end. 

Can you try the following steps next:
- try on another browser on same device or another device with safari. To see if it's browser or network related issue.
- take a debug WebGL build and read the console log to identify the problem.
- User `Zappar`  WebGL template on Unity 2020 and above and `Zappar2019` WebGL template on Unity 2019. You can't use the same template between unity 2019 and 2020.
- update your `manifest.json` under Packages folder to use the specific UAR version that was working. You can do this updating the git URL as following: 
`"com.zappar.uar": "https://github.com/zappar-xr/universal-ar-unity.git#3.0.0"`

If it still doesn't work please reach out to us via [forum ](https://forum.zap.works/) or [email ](mailto:support@zappar.com) where the support team can better assist with your project.

I'll be closing this issue now since this doesn't seem to be related to UAR and we can't reproduce it on our end. Feel free to reopen in case you find it related to UAR or specifying older version fixes your issue.

Regards,

**Closed as completed by nfynt-zap** 2021-12-21 17:30 UTC
